webtalk_init -webtalk_dir C:/Users/Zak/Desktop/master_2/projet/Program-synthesis-grom-Go-to-zyng-/exemple1/channel_design/channel_design.sim/sim_1/behav/xsim/xsim.dir/tb_channel_behav/webtalk/
webtalk_register_client -client project
webtalk_add_data -client project -key date_generated -value "Sat Feb 13 16:56:42 2021" -context "software_version_and_target_device"
webtalk_add_data -client project -key product_version -value "XSIM v2020.2 (64-bit)" -context "software_version_and_target_device"
webtalk_add_data -client project -key build_version -value "3064766" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_platform -value "WIN64" -context "software_version_and_target_device"
webtalk_add_data -client project -key registration_id -value "211968859_0_0_841" -context "software_version_and_target_device"
webtalk_add_data -client project -key tool_flow -value "xsim_vivado" -context "software_version_and_target_device"
webtalk_add_data -client project -key beta -value "FALSE" -context "software_version_and_target_device"
webtalk_add_data -client project -key route_design -value "FALSE" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_family -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_device -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_package -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_speed -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key random_id -value "9b06bc1a-817d-4770-a098-cac817f26ca7" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_id -value "9e51de10bca64ff2b638d5b8a1119c68" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_iteration -value "21" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_name -value "Windows Server 2016 or Windows 10" -context "user_environment"
webtalk_add_data -client project -key os_release -value "major release  (build 9200)" -context "user_environment"
webtalk_add_data -client project -key cpu_name -value "Intel(R) Core(TM) i5-3230M CPU @ 2.60GHz" -context "user_environment"
webtalk_add_data -client project -key cpu_speed -value "2594 MHz" -context "user_environment"
webtalk_add_data -client project -key total_processors -value "1" -context "user_environment"
webtalk_add_data -client project -key system_ram -value "8.000 GB" -context "user_environment"
webtalk_register_client -client xsim
webtalk_add_data -client xsim -key Command -value "xsim" -context "xsim\\command_line_options"
webtalk_add_data -client xsim -key trace_waveform -value "true" -context "xsim\\usage"
webtalk_add_data -client xsim -key runtime -value "10 us" -context "xsim\\usage"
webtalk_add_data -client xsim -key iteration -value "5" -context "xsim\\usage"
webtalk_add_data -client xsim -key Simulation_Time -value "0.08_sec" -context "xsim\\usage"
webtalk_add_data -client xsim -key Simulation_Memory -value "6420_KB" -context "xsim\\usage"
webtalk_transmit -clientid 3312024458 -regid "211968859_0_0_841" -xml C:/Users/Zak/Desktop/master_2/projet/Program-synthesis-grom-Go-to-zyng-/exemple1/channel_design/channel_design.sim/sim_1/behav/xsim/xsim.dir/tb_channel_behav/webtalk/usage_statistics_ext_xsim.xml -html C:/Users/Zak/Desktop/master_2/projet/Program-synthesis-grom-Go-to-zyng-/exemple1/channel_design/channel_design.sim/sim_1/behav/xsim/xsim.dir/tb_channel_behav/webtalk/usage_statistics_ext_xsim.html -wdm C:/Users/Zak/Desktop/master_2/projet/Program-synthesis-grom-Go-to-zyng-/exemple1/channel_design/channel_design.sim/sim_1/behav/xsim/xsim.dir/tb_channel_behav/webtalk/usage_statistics_ext_xsim.wdm -intro "<H3>XSIM Usage Report</H3><BR>"
webtalk_terminate
